domain: rotor

plugins:
  options:
    "@specss/css":
      themesFolder: "./ui/themes"
  # packages:
  #   - "@specss/docs"
    # - "@specss/minify"
    # - "@specss/postcss-autoprefixer"

global:
  cssVarsPrefix: "--myprefix"
  specsFolder: "./ui"
  outputFolder: "./dist"
