domain: mycompany

plugins:
  options:
    "@specss/css":
      themesFolder: "./design/themes"
  packages:
    - "@specss/docs"

global:
  cssVarsPrefix: "--mycompany"
  specsFolder: "./design"
  outputFolder: "./dist"
