domain: mycompany

plugins:
  options:
    "@specss/css":
      themesFolder: "./design/themes"
    "@specss/docs":
      foo: bar
  packages:
    - "@specss/docs"

global:
  cssVarsPrefix: "--rotor"
  specsFolder: "./design"
  outputFolder: "./dist"
