domain: mycompany

plugins:
  options:
    "@specss/css":
      themesFolder: "./design/themes"
  packages:
  #   - "@specss/docs"
    - "@specss/minify"

global:
  cssVarsPrefix: "--rotor"
  specsFolder: "./design"
  outputFolder: "./dist"
